# Generated by Django 5.0.6 on 2024-08-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_total_order_total_price_order_category_and_more'),
        ('orders', '0002_review'),
    ]

    operations = [
    ]
