# Generated by Django 4.2.15 on 2024-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='duration_first',
            field=models.CharField(blank=True, choices=[('once_a_week', 'Once a Week'), ('twice_a_week', 'Twice a Week')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='duration_second',
            field=models.CharField(blank=True, choices=[('one_month', 'One Month'), ('two_months', 'Two Months'), ('three_months', 'Three Months')], max_length=20, null=True),
        ),
    ]
