# Generated by Django 5.0.6 on 2024-08-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('sup', 'Supplier'), ('bus', 'Business Owner')], max_length=3),
        ),
    ]
