# Generated by Django 5.0.6 on 2024-08-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_bank_account_file_profile_cr_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Ahad', max_length=255),
            preserve_default=False,
        ),
    ]
