# Generated by Django 5.0.6 on 2024-08-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
