# Generated by Django 5.0.6 on 2024-08-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
